server:
  port: 8901


spring:
  datasource:
    url: jdbc:mysql://10.50.40.145:3306/dodo_db?characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowMultiQueries=true
    username: root
    password: cdwk-3g-145
    driver-class-name: com.mysql.jdbc.Driver
    #hikari 连接池
    hikari:
      #最小连接数
      minimum-idle: 5
      #池中最大连接数
      maximum-pool-size: 15
      # 从池返回的连接自动提交 (默认就为true,如果设置false则需要手动提交事务）
      auto-commit: true
      # 连接在池中闲置的最长时间 ms （此设置仅在minimumIdle定义为小于时适用maximumPoolSize。一旦池达到连接， 空闲连接将不会minimumIdle被淘汰）
      idle-timeout: 30000
      # 自定义连接池名 主要是为了日志记录
      pool-name: gateway-hikari
      # 控制池中连接的最大生存期 ms （连接如果在使用，则不会被淘汰
      max-lifetime: 120000
      # 等待获取池中连接最长时间 ms
      connection-timeout: 30000
      # 连接校验语句,判断连接是否可用
      connection-test-query: SELECT 1
  application:
    name: dodo-server-gateway
  cloud:
    nacos:
      # nacos 服务端地址
      server-addr: http://10.50.40.116:8765
#      server-addr: 10.50.40.116:8848,10.50.40.117:8848,10.50.40.145:8848
      discovery:
        ip: 10.50.40.113
    gateway:
      httpclient:
        connect-timeout: 3000
        response-timeout: 5000
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: location
          order: -1
          uri: lb://app-location-center
          predicates:
            - Path=/location/**
          filters:
            - StripPrefix=1
#            - AddResponseHeader=x-response,lei1


# 开启gateway端点查看,生产关闭
management:
  endpoint:
    gateway:
      # gateway 端点开启
      enabled: true
    shutdown:
      # 服务关闭 http://localhost:8901/actuator/shutdown
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
#        include: "gateway"







#mybatis-plus:
#  configuration:
#    ......
#  global-config:
#    ......
#    db-config:
#      ......
#  type-aliases-package: ""
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleteFlag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  type-aliases-package: com.leilei.gateway.entity.po
  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




